apiVersion: apps/v1

kind: Deployment

metadata:

  name: spring-app-deployment-kubernetes

spec:

  replicas: 2  # Number of pods

  selector:

    matchLabels:

      app: spring-app-kubernetes

  template:

    metadata:

      labels:

        app: spring-app-kubernetes

    spec:

      containers:

      - name: spring-app-kubernetes

        image: pannamrajesh/my-spring-boot-application:latest  # Docker image from Docker Hub

        ports:

        - containerPort: 8090


