version: '3'
services:
  deadpool:
    image: spring-application-java:latest  # Replace with the actual Spring Boot image name
    container_name: deadpool
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"  # Maps port 8080 inside the container to 8081 on the host

  batman:
    image: spring-application-java:latest  # Replace with the actual Spring Boot image name
    container_name: batman
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"  # Maps port 8080 inside the container to 8082 on the host
