apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  type: LoadBalancer # Use LoadBalancer to expose the service
  ports:
  - port: 80  # External port
    targetPort: 8090  # Port on the container
    nodePort: 30001
  selector:
    app: spring-app-kubernetes


